#!/usr/bin/env python3
"""
Fit effective-mass tensors from a VASP EIGENVAL file produced using KPOINTS generated by
`generate_vasp_mass_kpoints.py`.

Units:
- dk_cart_Ainv in metadata: Angstrom^{-1}
- energies in EIGENVAL: eV
- Hessian eigenvalues: eV Angstrom^2
- masses are reported in units of m0.
"""
import argparse, json
from pathlib import Path
import numpy as np

HBAR2_OVER_M0 = 7.619964  # eV Angstrom^2


def read_poscar_lattice(path):
    lines = Path(path).read_text().splitlines()
    scale = float(lines[1].split()[0])
    A = np.array([[float(x) for x in lines[i].split()[:3]] for i in range(2, 5)], dtype=float) * scale
    return A


def read_eigenval(path, spin=1):
    lines = Path(path).read_text().splitlines()
    # Header line 6 normally: NELECT NKPTS NBANDS
    nelect, nkpts, nbands = [int(float(x)) for x in lines[5].split()[:3]]
    energies = np.zeros((nkpts, nbands), dtype=float)
    occs = np.full((nkpts, nbands), np.nan, dtype=float)
    kpts = np.zeros((nkpts, 3), dtype=float)
    idx = 6
    for ik in range(nkpts):
        # skip blank lines
        while idx < len(lines) and not lines[idx].split():
            idx += 1
        parts = lines[idx].split()
        kpts[ik] = [float(parts[0]), float(parts[1]), float(parts[2])]
        idx += 1
        for ib in range(nbands):
            parts = lines[idx].split()
            # non-spin: band energy occ ; spin: band eup edown occ_up occ_down
            if len(parts) >= 5:
                if spin == 1:
                    energies[ik, ib] = float(parts[1]); occs[ik, ib] = float(parts[3])
                elif spin == 2:
                    energies[ik, ib] = float(parts[2]); occs[ik, ib] = float(parts[4])
                else:
                    energies[ik, ib] = 0.5 * (float(parts[1]) + float(parts[2]))
                    occs[ik, ib] = 0.5 * (float(parts[3]) + float(parts[4]))
            else:
                energies[ik, ib] = float(parts[1]); occs[ik, ib] = float(parts[2])
            idx += 1
    return nelect, nkpts, nbands, kpts, energies, occs


def fit_hessian(dk_cart, E):
    dk_cart = np.asarray(dk_cart, dtype=float)
    E = np.asarray(E, dtype=float)
    x, y, z = dk_cart[:, 0], dk_cart[:, 1], dk_cart[:, 2]
    X = np.column_stack([
        np.ones_like(x),
        x, y, z,
        0.5*x*x, 0.5*y*y, 0.5*z*z,
        x*y, x*z, y*z,
    ])
    coeff, residuals, rank, svals = np.linalg.lstsq(X, E, rcond=None)
    H = np.array([
        [coeff[4], coeff[7], coeff[8]],
        [coeff[7], coeff[5], coeff[9]],
        [coeff[8], coeff[9], coeff[6]],
    ], dtype=float)
    grad = coeff[1:4]
    # Stationary point displacement relative to the supplied k0.
    try:
        shift = -np.linalg.solve(H, grad)
    except np.linalg.LinAlgError:
        shift = np.array([np.nan, np.nan, np.nan])
    fit = X @ coeff
    rms = np.sqrt(np.mean((E - fit)**2))
    return H, grad, shift, rms, coeff


def mass_report(name, H, kind, field_hat=None):
    if kind == "electron":
        C = H
        sign_text = "conduction/electron"
    elif kind == "hole":
        C = -H
        sign_text = "valence/hole, using -H_v"
    else:
        raise ValueError(kind)
        
    eigvals, eigvecs = np.linalg.eigh(C)
    masses = HBAR2_OVER_M0 / eigvals
    mdos = np.prod(masses) ** (1.0/3.0) if np.all(masses > 0) else np.nan
    
    print(f"\n[{name}] {sign_text}")
    print(f"DOS effective mass (single valley) /m0: {mdos:.8g}")
    for label, fhat in [("x", np.array([1.0,0,0])), ("y", np.array([0,1.0,0])), ("z", np.array([0,0,1.0]))]:
        curv = float(fhat @ C @ fhat)
        print(f"m_parallel along Cartesian {label} /m0: {HBAR2_OVER_M0/curv:.8g}")
    if field_hat is not None:
        curv = float(field_hat @ C @ field_hat)
        print(f"m_parallel along requested field /m0: {HBAR2_OVER_M0/curv:.8g}")
    return masses, mdos


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--eigenval", default="EIGENVAL")
    ap.add_argument("--metadata", required=True)
    ap.add_argument("--cband", type=int, required=True, help="1-based VASP band index for CBM band near Gamma")
    ap.add_argument("--vband", type=int, required=True, help="1-based VASP band index for VBM band near the VBM k-point")
    ap.add_argument("--spin", type=int, default=1, help="1 or 2 for spin-polarized EIGENVAL; use 0 to average spin channels")
    ap.add_argument("--poscar", default=None, help="needed only for --field-direct")
    ap.add_argument("--field-cart", nargs=3, type=float, default=None, help="field direction in Cartesian coordinates")
    ap.add_argument("--field-direct", nargs=3, type=float, default=None, help="field direction as real-space lattice-vector coefficients [u v w]")
    args = ap.parse_args()

    meta = json.loads(Path(args.metadata).read_text())
    nelect, nkpts, nbands, kpts, energies, occs = read_eigenval(args.eigenval, spin=args.spin)
    points = meta["points"]
    if len(points) != nkpts:
        raise RuntimeError(f"metadata has {len(points)} points but EIGENVAL has {nkpts} k-points")

    field_hat = None
    if args.field_cart is not None:
        field_hat = np.array(args.field_cart, dtype=float)
    elif args.field_direct is not None:
        poscar = args.poscar or meta.get("poscar")
        A = read_poscar_lattice(poscar)
        # row-vector convention: cart = coeff @ A
        field_hat = np.array(args.field_direct, dtype=float) @ A
    if field_hat is not None:
        field_hat = field_hat / np.linalg.norm(field_hat)
        print("Requested field unit vector, Cartesian:", field_hat)

    results = {}
    for group, band, kind in [("CBM", args.cband, "electron"), ("VBM", args.vband, "hole")]:
        idxs = [i for i, p in enumerate(points) if p["group"] == group]
        dk = np.array([points[i]["dk_cart_Ainv"] for i in idxs], dtype=float)
        E = energies[idxs, band-1]
        H, grad, shift, rms, coeff = fit_hessian(dk, E)
        print(f"\nFit group {group}, band {band}")
        masses, mdos = mass_report(group, H, kind, field_hat=field_hat)
        results[group] = {"H": H, "masses": masses, "mdos": mdos}

    if field_hat is not None:
        Hc = results["CBM"]["H"]
        Hv = results["VBM"]["H"]
        mc = HBAR2_OVER_M0 / float(field_hat @ Hc @ field_hat)
        mv = HBAR2_OVER_M0 / float(field_hat @ (-Hv) @ field_hat)
        mr = mc * mv / (mc + mv)
        
        print("\nReduced mass along requested field:")
        print(f"m_c_parallel/m0 = {mc:.8g}")
        print(f"m_v_parallel/m0 = {mv:.8g}")
        print(f"m_r_parallel/m0 = {mr:.8g}")


if __name__ == "__main__":
    main()
